In [1]:
import pandas as pd
from sklearn.model_selection import KFold #This is for the K-Fold Cross Validation
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

In [2]:
data=pd.read_csv(r"D:\GIT\Workshop Python\Data\Boston.csv")
data.head()

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

# Creating K-Fold Corss Validation object with 5 folds. You can use any number of folds

In [4]:
kf=KFold(n_splits=5,shuffle=True)
kf

KFold(n_splits=5, random_state=None, shuffle=True)

In [5]:
model=LinearRegression()
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Split function is used to separet the training and testing data in each fold

In [6]:
kf.split(data) #This returns the indexes of training & testing data for each fold

In [7]:
list(kf.split(data))

[(array([  0,   1,   4,   5,   6,   8,   9,  11,  13,  14,  15,  16,  18,
          19,  21,  22,  23,  24,  25,  26,  28,  29,  30,  31,  32,  34,
          35,  36,  37,  38,  39,  40,  42,  43,  45,  46,  47,  48,  49,
          50,  51,  52,  53,  54,  56,  57,  60,  61,  62,  63,  64,  65,
          66,  67,  69,  70,  71,  72,  74,  75,  76,  77,  78,  79,  81,
          82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  95,
          96,  98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
         111, 113, 114, 117, 118, 119, 120, 121, 122, 124, 125, 126, 127,
         128, 129, 131, 132, 133, 134, 136, 137, 139, 140, 141, 142, 143,
         144, 145, 147, 149, 150, 151, 152, 153, 155, 156, 157, 159, 160,
         162, 163, 164, 166, 167, 168, 171, 172, 173, 174, 177, 178, 179,
         180, 181, 183, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
         196, 197, 198, 199, 200, 201, 202, 203, 204, 207, 208, 209, 210,
         211, 213, 214, 215, 217, 218, 219, 220, 221, 223, 224, 225, 227,
         230, 231, 232, 235, 236, 237, 238, 239, 240, 241, 243, 244, 245,
         247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 258, 259, 260,
         261, 264, 265, 266, 267, 268, 269, 271, 272, 273, 274, 275, 276,
         277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 288, 289, 290,
         291, 292, 293, 294, 295, 296, 297, 298, 299, 301, 304, 305, 308,
         309, 310, 311, 312, 314, 315, 316, 318, 319, 321, 322, 324, 325,
         326, 327, 328, 329, 330, 331, 332, 333, 335, 336, 337, 338, 339,
         340, 341, 342, 343, 344, 345, 346, 348, 349, 350, 351, 352, 353,
         354, 356, 357, 358, 359, 360, 361, 362, 363, 364, 366, 367, 368,
         369, 370, 372, 373, 375, 377, 378, 379, 381, 382, 383, 384, 385,
         386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398,
         399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 411, 412, 413,
         414, 416, 417, 419, 421, 422, 424, 427, 428, 429, 430, 431, 433,
         434, 436, 437, 438, 440, 441, 442, 443, 444, 445, 446, 449, 450,
         451, 452, 453, 454, 455, 456, 458, 459, 462, 463, 464, 467, 468,
         469, 470, 471, 473, 474, 475, 476, 477, 479, 480, 481, 482, 483,
         484, 486, 487, 489, 490, 496, 497, 498, 499, 500, 501, 503, 504,
         505]),
  array([  2,   3,   7,  10,  12,  17,  20,  27,  33,  41,  44,  55,  58,
          59,  68,  73,  80,  94,  97,  99, 112, 115, 116, 123, 130, 135,
         138, 146, 148, 154, 158, 161, 165, 169, 170, 175, 176, 182, 184,
         195, 205, 206, 212, 216, 222, 226, 228, 229, 233, 234, 242, 246,
         257, 262, 263, 270, 287, 300, 302, 303, 306, 307, 313, 317, 320,
         323, 334, 347, 355, 365, 371, 374, 376, 380, 409, 410, 415, 418,
         420, 423, 425, 426, 432, 435, 439, 447, 448, 457, 460, 461, 465,
         466, 472, 478, 485, 488, 491, 492, 493, 494, 495, 502])),
 (array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  13,  14,  15,
          17,  18,  19,  20,  21,  23,  24,  25,  27,  30,  32,  33,  34,
          36,  37,  41,  42,  43,  44,  46,  48,  50,  51,  53,  55,  57,
          58,  59,  60,  61,  62,  63,  64,  66,  67,  68,  69,  70,  71,
          73,  74,  75,  76,  77,  78,  79,  80,  82,  83,  84,  85,  87,
          89,  92,  93,  94,  96,  97,  98,  99, 100, 102, 103, 104, 106,
         107, 109, 110, 111, 112, 114, 115, 116, 117, 118, 119, 120, 122,
         123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 143, 144, 145, 146, 147, 148, 149, 150,
         152, 154, 156, 157, 158, 159, 161, 163, 165, 166, 167, 169, 170,
         171, 172, 175, 176, 177, 179, 182, 183, 184, 186, 189, 190, 191,
         193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 205, 206,
         207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,
         222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
         235, 236, 237, 238, 239, 240, 241, 242, 245, 246, 247, 248, 249,
         250, 251, 252, 253, 254, 256, 257, 258, 259, 260, 261, 262, 263,
         264, 265, 266, 267, 268, 269, 270, 272, 273, 274, 276, 277, 278,
         280, 281, 282, 283, 285, 286, 287, 288, 289, 293, 294, 295, 296,
         297, 298, 299, 300, 302, 303, 306, 307, 308, 309, 310, 312, 313,
         314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326,
         327, 328, 329, 330, 331, 332, 334, 335, 336, 337, 339, 340, 342,
         344, 346, 347, 348, 349, 350, 351, 352, 353, 355, 357, 358, 359,
         360, 361, 362, 364, 365, 366, 367, 368, 369, 370, 371, 373, 374,
         375, 376, 378, 379, 380, 381, 382, 383, 385, 386, 389, 390, 392,
         393, 394, 395, 396, 397, 399, 401, 402, 403, 405, 406, 407, 408,
         409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 422,
         423, 424, 425, 426, 427, 429, 430, 431, 432, 433, 434, 435, 436,
         437, 438, 439, 441, 442, 444, 445, 447, 448, 449, 450, 451, 455,
         456, 457, 458, 459, 460, 461, 462, 463, 465, 466, 467, 468, 469,
         470, 471, 472, 474, 475, 476, 477, 478, 480, 481, 482, 484, 485,
         486, 487, 488, 489, 491, 492, 493, 494, 495, 498, 499, 501, 502,
         503, 504]),
  array([  0,   1,  11,  16,  22,  26,  28,  29,  31,  35,  38,  39,  40,
          45,  47,  49,  52,  54,  56,  65,  72,  81,  86,  88,  90,  91,
          95, 101, 105, 108, 113, 121, 141, 142, 151, 153, 155, 160, 162,
         164, 168, 173, 174, 178, 180, 181, 185, 187, 188, 192, 204, 220,
         221, 243, 244, 255, 271, 275, 279, 284, 290, 291, 292, 301, 304,
         305, 311, 333, 338, 341, 343, 345, 354, 356, 363, 372, 377, 384,
         387, 388, 391, 398, 400, 404, 421, 428, 440, 443, 446, 452, 453,
         454, 464, 473, 479, 483, 490, 496, 497, 500, 505])),
 (array([  0,   1,   2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,
          16,  17,  18,  20,  21,  22,  24,  25,  26,  27,  28,  29,  31,
          33,  35,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49,  51,  52,  54,  55,  56,  58,  59,  60,  61,  62,  63,
          64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  77,
          78,  79,  80,  81,  83,  84,  86,  87,  88,  90,  91,  92,  94,
          95,  97,  98,  99, 101, 102, 103, 105, 106, 107, 108, 109, 111,
         112, 113, 115, 116, 117, 118, 119, 120, 121, 123, 125, 126, 129,
         130, 132, 135, 136, 137, 138, 140, 141, 142, 143, 144, 145, 146,
         147, 148, 151, 153, 154, 155, 156, 157, 158, 160, 161, 162, 163,
         164, 165, 166, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
         178, 180, 181, 182, 183, 184, 185, 187, 188, 189, 190, 191, 192,
         193, 194, 195, 197, 199, 200, 202, 204, 205, 206, 207, 208, 209,
         210, 212, 213, 214, 216, 217, 218, 219, 220, 221, 222, 223, 224,
         225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 239,
         241, 242, 243, 244, 246, 247, 248, 254, 255, 256, 257, 258, 260,
         261, 262, 263, 264, 265, 266, 267, 268, 270, 271, 272, 273, 274,
         275, 276, 278, 279, 280, 283, 284, 286, 287, 290, 291, 292, 293,
         294, 295, 296, 299, 300, 301, 302, 303, 304, 305, 306, 307, 309,
         310, 311, 312, 313, 314, 315, 317, 319, 320, 323, 324, 329, 330,
         332, 333, 334, 335, 336, 338, 340, 341, 343, 344, 345, 346, 347,
         348, 349, 350, 353, 354, 355, 356, 357, 358, 359, 360, 362, 363,
         365, 367, 368, 369, 370, 371, 372, 373, 374, 376, 377, 378, 380,
         381, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395,
         396, 397, 398, 399, 400, 402, 403, 404, 405, 406, 407, 408, 409,
         410, 411, 412, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423,
         424, 425, 426, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437,
         438, 439, 440, 441, 442, 443, 445, 446, 447, 448, 449, 451, 452,
         453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465,
         466, 467, 469, 472, 473, 474, 475, 478, 479, 480, 483, 485, 487,
         488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 499, 500, 501,
         502, 505]),
  array([  5,  14,  15,  19,  23,  30,  32,  34,  36,  50,  53,  57,  76,
          82,  85,  89,  93,  96, 100, 104, 110, 114, 122, 124, 127, 128,
         131, 133, 134, 139, 149, 150, 152, 159, 167, 179, 186, 196, 198,
         201, 203, 211, 215, 237, 238, 240, 245, 249, 250, 251, 252, 253,
         259, 269, 277, 281, 282, 285, 288, 289, 297, 298, 308, 316, 318,
         321, 322, 325, 326, 327, 328, 331, 337, 339, 342, 351, 352, 361,
         364, 366, 375, 379, 382, 383, 401, 413, 427, 444, 450, 468, 470,
         471, 476, 477, 481, 482, 484, 486, 498, 503, 504])),
 (array([  0,   1,   2,   3,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  38,  39,  40,  41,
          43,  44,  45,  47,  48,  49,  50,  52,  53,  54,  55,  56,  57,
          58,  59,  61,  63,  64,  65,  67,  68,  69,  70,  71,  72,  73,
          74,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
          88,  89,  90,  91,  93,  94,  95,  96,  97,  98,  99, 100, 101,
         103, 104, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
         118, 120, 121, 122, 123, 124, 126, 127, 128, 130, 131, 132, 133,
         134, 135, 136, 138, 139, 140, 141, 142, 145, 146, 148, 149, 150,
         151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 164,
         165, 167, 168, 169, 170, 173, 174, 175, 176, 177, 178, 179, 180,
         181, 182, 183, 184, 185, 186, 187, 188, 191, 192, 194, 195, 196,
         197, 198, 201, 202, 203, 204, 205, 206, 207, 208, 210, 211, 212,
         215, 216, 220, 221, 222, 223, 226, 228, 229, 232, 233, 234, 235,
         236, 237, 238, 240, 241, 242, 243, 244, 245, 246, 248, 249, 250,
         251, 252, 253, 255, 256, 257, 258, 259, 260, 262, 263, 265, 266,
         268, 269, 270, 271, 273, 275, 277, 278, 279, 281, 282, 284, 285,
         287, 288, 289, 290, 291, 292, 294, 297, 298, 299, 300, 301, 302,
         303, 304, 305, 306, 307, 308, 310, 311, 312, 313, 316, 317, 318,
         319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 330, 331, 333,
         334, 336, 337, 338, 339, 341, 342, 343, 344, 345, 347, 348, 351,
         352, 354, 355, 356, 360, 361, 362, 363, 364, 365, 366, 369, 370,
         371, 372, 374, 375, 376, 377, 379, 380, 382, 383, 384, 385, 386,
         387, 388, 391, 392, 393, 394, 397, 398, 400, 401, 404, 406, 408,
         409, 410, 411, 412, 413, 415, 416, 418, 420, 421, 423, 424, 425,
         426, 427, 428, 429, 432, 433, 435, 437, 439, 440, 441, 442, 443,
         444, 445, 446, 447, 448, 450, 452, 453, 454, 455, 456, 457, 459,
         460, 461, 462, 463, 464, 465, 466, 468, 470, 471, 472, 473, 476,
         477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 488, 489, 490,
         491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503,
         504, 505]),
  array([  4,  18,  37,  42,  46,  51,  60,  62,  66,  75,  92, 102, 106,
         117, 119, 125, 129, 137, 143, 144, 147, 163, 166, 171, 172, 189,
         190, 193, 199, 200, 209, 213, 214, 217, 218, 219, 224, 225, 227,
         230, 231, 239, 247, 254, 261, 264, 267, 272, 274, 276, 280, 283,
         286, 293, 295, 296, 309, 314, 315, 329, 332, 335, 340, 346, 349,
         350, 353, 357, 358, 359, 367, 368, 373, 378, 381, 389, 390, 395,
         396, 399, 402, 403, 405, 407, 414, 417, 419, 422, 430, 431, 434,
         436, 438, 449, 451, 458, 467, 469, 474, 475, 487])),
 (array([  0,   1,   2,   3,   4,   5,   7,  10,  11,  12,  14,  15,  16,
          17,  18,  19,  20,  22,  23,  26,  27,  28,  29,  30,  31,  32,
          33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  44,  45,  46,
          47,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
          62,  65,  66,  68,  72,  73,  75,  76,  80,  81,  82,  85,  86,
          88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  99, 100, 101,
         102, 104, 105, 106, 108, 110, 112, 113, 114, 115, 116, 117, 119,
         121, 122, 123, 124, 125, 127, 128, 129, 130, 131, 133, 134, 135,
         137, 138, 139, 141, 142, 143, 144, 146, 147, 148, 149, 150, 151,
         152, 153, 154, 155, 158, 159, 160, 161, 162, 163, 164, 165, 166,
         167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 178, 179, 180,
         181, 182, 184, 185, 186, 187, 188, 189, 190, 192, 193, 195, 196,
         198, 199, 200, 201, 203, 204, 205, 206, 209, 211, 212, 213, 214,
         215, 216, 217, 218, 219, 220, 221, 222, 224, 225, 226, 227, 228,
         229, 230, 231, 233, 234, 237, 238, 239, 240, 242, 243, 244, 245,
         246, 247, 249, 250, 251, 252, 253, 254, 255, 257, 259, 261, 262,
         263, 264, 267, 269, 270, 271, 272, 274, 275, 276, 277, 279, 280,
         281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
         295, 296, 297, 298, 300, 301, 302, 303, 304, 305, 306, 307, 308,
         309, 311, 313, 314, 315, 316, 317, 318, 320, 321, 322, 323, 325,
         326, 327, 328, 329, 331, 332, 333, 334, 335, 337, 338, 339, 340,
         341, 342, 343, 345, 346, 347, 349, 350, 351, 352, 353, 354, 355,
         356, 357, 358, 359, 361, 363, 364, 365, 366, 367, 368, 371, 372,
         373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 387,
         388, 389, 390, 391, 395, 396, 398, 399, 400, 401, 402, 403, 404,
         405, 407, 409, 410, 413, 414, 415, 417, 418, 419, 420, 421, 422,
         423, 425, 426, 427, 428, 430, 431, 432, 434, 435, 436, 438, 439,
         440, 443, 444, 446, 447, 448, 449, 450, 451, 452, 453, 454, 457,
         458, 460, 461, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473,
         474, 475, 476, 477, 478, 479, 481, 482, 483, 484, 485, 486, 487,
         488, 490, 491, 492, 493, 494, 495, 496, 497, 498, 500, 502, 503,
         504, 505]),
  array([  6,   8,   9,  13,  21,  24,  25,  43,  48,  61,  63,  64,  67,
          69,  70,  71,  74,  77,  78,  79,  83,  84,  87,  98, 103, 107,
         109, 111, 118, 120, 126, 132, 136, 140, 145, 156, 157, 177, 183,
         191, 194, 197, 202, 207, 208, 210, 223, 232, 235, 236, 241, 248,
         256, 258, 260, 265, 266, 268, 273, 278, 294, 299, 310, 312, 319,
         324, 330, 336, 344, 348, 360, 362, 369, 370, 385, 386, 392, 393,
         394, 397, 406, 408, 411, 412, 416, 424, 429, 433, 437, 441, 442,
         445, 455, 456, 459, 462, 463, 480, 489, 499, 501]))]

# Training the model with training set and validating with testing set in each fold and appending RSquared Value & MSE for each fold

In [8]:
MSEL=[]
RSL=[]

In [9]:
for i in list(kf.split(data)):
    model.fit(x[i[0],:],y[i[0]])
    RSL.append(model.score(x[i[0],:],y[i[0]]))
    y_pred=model.predict(x[i[1],:])
    MSEL.append(np.sqrt(mean_squared_error(y_pred,y[i[1]])))

# R-Squared value with Cross Validation

In [10]:
np.mean(RSL)*100

73.74092709576318

# Mean Squared Error with Cross Validation

In [11]:
np.mean(MSEL)

4.869281003689737